FROM apache/airflow:2.8.1-python3.11

RUN pip install --no-cache-dir \
    airflow-clickhouse-plugin \
    pandas \
    requests \
    clickhouse_driver \
    "pyiceberg[s3fs,rest,pyarrow]==0.6.1" \
    boto3 \
    dbt-core==1.8.7 \
    dbt-clickhouse==1.8.2 \
    clickhouse-connect==0.7.16
