name: 'citibike_weather'
version: '1.0.0'
config-version: 2
profile: 'citibike_weather'
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
docs-paths: ["docs"]
target-path: "target"
clean-targets: ["target"]

models:
  citibike_weather:
    bronze:
      +materialized: table
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold