name: 'citibike_weather'
version: '1.0.0'
config-version: 2

profile: 'citibike_weather'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  citibike_weather:
    staging:
      materialized: view
    gold:
      materialized: table
