citibike_weather:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: citibike
      host: clickhouse-server
      port: 8123
      user: admin
      password: ""
      secure: False
      threads: 4