citibike_weather:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: clickhouse-server
      port: 8123
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      secure: false
      database: default