citibike_weather:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: clickhouse-server
      port: 9000
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', '') }}"
      secure: false